### PR TITLE
Add popular posts from r/AWS.

### PR DESCRIPTION
**Pull request by rowanu**
Remove trailing whitespace.

### CODE REVIEW

**Comment by rjhintz** [comment]
I, for one, have been submitting links both in Reddit ( /r/aws) and separately as PRs here, so there end up being conflicting duplicates. 

It might make sense to have the standard be to submit links individually. This would resolve issues with a PR where one link conflicts, but another doesn't. Hard to enforce, though.

**Comment by rowanu** [comment]
Conflicts happen, it's no big deal. I should've checked before submitting this PR (I just did it quickly from my local copy instead of through the web interface).

I'll clean mine up.

**Comment by jeffbarr** [comment]
Hi Rowan, multiple links per PR are fine, whatever is easiest for you. I am still learning how to use Git and to run an open source project and a little bit of variety with respect to the structure of the contributions (1 vs. multiple) is instructive. Thanks so much for your help!

**Comment by rjhintz** [comment]
Just to remark that I'm not trying for the free lunch by proposing a zillion individual links instead of aggregating. I'm just a big believer in small changes (and overfed anyway, so won't be attending).

**Pull request closed without merging**
