### PR TITLE
Added interview with teen who created CloudStatus Alexa skill using AWS Lambda

### PR DESCRIPTION
**Pull request by ehammond**

### CODE REVIEW

**Comment by rjhintz** [comment]
@ehammond 
Glad that you added this (and mentored the project). Very interesting effort, regardless of teen or adult.

**Comment by ehammond** [comment]
Thanks, @rjhintz . I tried to promote the project on its own merit (and I think it has utility for AWS developers) but the human interest angle seems to grab orders of magnitude more interest.

**Comment by rjhintz** [comment]
@ehammond Actually I started reading it as a teen level project, but was really pleased to see it was anything but and had professional level utility. Good writeup with the interview style, too. 

I'll reference it on Reddit in the AWS sub, though the audience is kinda hit and miss there. I referenced a Scott Lowe article on Vagrant/AWS recently and it got downvoted. :(

**Comment by jeffbarr** [comment]
Got it, thanks Eric!

**Pull request closed without merging**
