### PR TITLE
added cloudonaut's article: Wordpress on AWS: smooth and pain free

### PR DESCRIPTION
**Pull request by andreaswittig**
Weekly blog post from [cloudonaut.io](https://cloudonaut.io).

### CODE REVIEW

**Comment by rowanu** [comment]
Beat you to it #347 😉 

I came across it via [r/aws](https://www.reddit.com/r/aws/comments/5ae5uu/wordpress_on_aws_smooth_and_pain_free/).

**Comment by andreaswittig** [comment]
@rowanu You should let the author go ahead. 😇

**Comment by rowanu** [comment]
Whoops, forgot to do that yesterday!

Big fan of your blog, keep the posts coming.

**Comment by andreaswittig** [comment]
👍

**Comment by jeffbarr** [comment]
Thank you all for working together to make the AWS Week in Review a big success, greatly appreciated!

**Pull request closed without merging**
